# A simple Makefile
# Jafar Moukalled       G01110547
# CS262, Lab Section 223
# GMU Delivery

CC = gcc -g

CFLAGS=-pedantic-errors -Og
TARGET=GMUDelivery
all: $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm $(TARGET)
